import moment from 'moment';
import {EventStatus} from './Constants';
const dataHrEvent = [
  {
    id: 1,
    eventName: 'Galas and Casual',
    vendorName: 'Alexis Riley',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 2,
    eventName: 'Oliver',
    vendorName: 'Amelia',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.APPROVED,
  },
  {
    id: 3,
    eventName: 'Jack',
    vendorName: 'Olivia',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.APPROVED,
  },
  {
    id: 4,
    eventName: 'Harry',
    vendorName: 'Poppy',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.APPROVED,
  },
  {
    id: 5,
    eventName: 'Jacobl',
    vendorName: 'Bethany',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.APPROVED,
  },
  {
    id: 6,
    eventName: 'Charliel',
    vendorName: 'Sophia',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 7,
    eventName: 'Thomas',
    vendorName: 'Mia',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 8,
    eventName: 'George',
    vendorName: 'Linda',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 9,
    eventName: 'Oscar',
    vendorName: 'Barbara',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 10,
    eventName: 'James',
    vendorName: 'Patricia',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 11,
    eventName: 'William',
    vendorName: 'Mary',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 12,
    eventName: 'Jake',
    vendorName: 'Barbara',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 13,
    eventName: 'Connor	',
    vendorName: 'Susan',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 14,
    eventName: 'Callum',
    vendorName: 'Margaret',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 15,
    eventName: 'Kyle',
    vendorName: 'Jessica',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 16,
    eventName: 'Joe',
    vendorName: 'Jennifer',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 17,
    eventName: 'Reece',
    vendorName: 'Isabella',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 18,
    eventName: 'Charlie',
    vendorName: 'Smith',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 19,
    eventName: 'Damian',
    vendorName: 'Johnson',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
  {
    id: 20,
    eventName: 'Daniel',
    vendorName: 'Brown',
    createdDate: '01/15/2020',
    confirmDate: moment().subtract(10, 'days').calendar(),
    status: EventStatus.PENDING,
  },
];

export {dataHrEvent};
